version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acl-php
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
  web:
    image: nginx:alpine
    container_name: acl-nginx
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - app
    networks:
      - app-network
  db:
    image: mysql:8.0
    container_name: acl-mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acl_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: acl-mysql
    ports:
      - "1750:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
